<?php
$waitingFilters = ['workspace'=>'1','tab'=>$waitingSchedule ? 'schedule' : 'waiting','q'=>$waitingSearch,'from_date'=>$waitingFrom,'to_date'=>$waitingTo,'status'=>$waitingStatus,'per_page'=>$waitingPerPage];
?>
<style>
    .doctor-waiting-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:16px 0}.doctor-waiting-summary div{padding:14px 16px;border:1px solid var(--border-ui);border-radius:10px;background:#fff}.doctor-waiting-summary span{display:block;color:var(--text-muted);font-size:12px}.doctor-waiting-summary strong{display:block;margin-top:4px;font-size:24px;color:var(--primary)}.doctor-schedule-modal{display:none;position:fixed;z-index:1300;top:14vh;left:50%;width:min(520px,calc(100vw - 28px));transform:translateX(-50%);padding:20px;border:1px solid var(--border-ui);border-radius:12px;background:#fff;box-shadow:0 20px 60px rgba(0,0,0,.28)}.doctor-schedule-modal.is-open{display:block}.doctor-schedule-modal dl{display:grid;grid-template-columns:150px minmax(0,1fr);gap:12px 18px;margin:18px 0}.doctor-schedule-modal dt{font-weight:700;color:var(--text-muted);align-self:center}.doctor-schedule-modal dd{margin:0;align-self:center}.doctor-schedule-badge{display:inline-flex;align-items:center;min-height:26px;padding:4px 9px;border-radius:999px;font-size:12px;font-weight:700}.doctor-schedule-badge.payment-paid{background:#dcfce7;color:#166534}.doctor-schedule-badge.payment-partial{background:#fef3c7;color:#92400e}.doctor-schedule-badge.payment-unpaid{background:#fee2e2;color:#991b1b}.doctor-schedule-badge.queue-waiting{background:#dbeafe;color:#1d4ed8}.doctor-schedule-badge.queue-consultation{background:#e0e7ff;color:#3730a3}.doctor-schedule-badge.queue-completed{background:#dcfce7;color:#166534}.doctor-schedule-badge.queue-cancelled{background:#f3f4f6;color:#4b5563}.waiting-toolbar{align-items:end}.waiting-toolbar label{min-width:130px}.waiting-toolbar label.waiting-search{flex:1 1 220px}.waiting-toolbar input,.waiting-toolbar select,.waiting-toolbar .btn,.waiting-toolbar .export-group{height:38px;min-height:38px;box-sizing:border-box}.waiting-toolbar .export-group{display:flex;align-items:center;gap:8px}.waiting-toolbar .export-group .btn{height:38px}.doctor-schedule-close{float:right;border:0;background:transparent;font-size:24px;cursor:pointer}@media(max-width:700px){.doctor-waiting-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.doctor-schedule-modal dl{grid-template-columns:1fr}}
</style>
<section class="waiting-screen">
    <nav class="setup-section-nav no-print" aria-label="Clinical work"><a href="doctors.php?workspace=1" <?= !$waitingSchedule ? 'class="active" aria-current="page"' : '' ?>>Patient Waiting</a><a href="doctors.php?workspace=1&amp;tab=schedule" <?= $waitingSchedule ? 'class="active" aria-current="page"' : '' ?>>My Schedule</a></nav>
    <h2><?= $waitingSchedule ? 'My Schedule' : 'Patient Waiting' ?></h2>
    <p class="welcome-sub"><?= $waitingSchedule ? 'Read-only appointments assigned to you.' : 'Operational clinical queue with active and completed visits.' ?></p>
    <?php if (!$waitingSchedule): ?><div class="doctor-waiting-summary" aria-label="Patient Waiting summary"><div><span>Waiting</span><strong><?= (int) $waitingSummary['waiting'] ?></strong></div><div><span>In Consultation</span><strong><?= (int) $waitingSummary['consultation'] ?></strong></div><div><span>Completed Today</span><strong><?= (int) $waitingSummary['completed'] ?></strong></div><div><span>Outstanding Due</span><strong><?= number_format((float) $waitingSummary['due'], 2) ?></strong></div></div><?php endif; ?>
    <?php if ($waitingDateError): ?><div class="error-msg" role="alert"><?= tdc_e($waitingDateError) ?></div><?php endif; ?>
    <form method="get" class="waiting-toolbar no-print">
        <input type="hidden" name="workspace" value="1">
        <input type="hidden" name="tab" value="<?= $waitingSchedule ? 'schedule' : 'waiting' ?>">
        <label>Show <select name="per_page"><?php foreach ([10,25,50,100] as $size): ?><option <?= $size === $waitingPerPage ? 'selected' : '' ?>><?= $size ?></option><?php endforeach; ?></select> entries</label>
        <label>From Date <input type="date" name="from_date" value="<?= tdc_e($waitingFrom) ?>"></label>
        <label>To Date <input type="date" name="to_date" value="<?= tdc_e($waitingTo) ?>"></label>
        <?php if ($waitingSchedule): ?><label>Status <select name="status"><option value="">All statuses</option><?php foreach (['Waiting','In Consultation','Completed','Cancelled'] as $status): ?><option value="<?= tdc_e($status) ?>" <?= $waitingStatus === $status ? 'selected' : '' ?>><?= tdc_e($status) ?></option><?php endforeach; ?></select></label><?php endif; ?>
        <label class="waiting-search">Search <input type="search" name="q" value="<?= tdc_e($waitingSearch) ?>" placeholder="Search by appointment, patient, phone..."></label>
        <button class="btn btn-primary">Apply</button>
        <?= tdc_export_buttons(['csv'=>'doctors.php?'.http_build_query($waitingFilters + ['export'=>'csv'])]) ?>
    </form>
    <div class="data-table-wrap"><table class="data-table">
        <?php if ($waitingSchedule): ?><thead><tr><th>Visit Ref</th><th>Patient</th><th>Date</th><th>Time</th><th>Payment</th><th>Due</th><th>Queue Status</th><th class="no-print">View</th></tr></thead>
        <?php else: ?><thead><tr><th>Visit Ref</th><th>Patient</th><th>Gender</th><th>Age</th><th>Phone</th><th>Visit Date</th><th>Payment</th><th>Due</th><th>Queue Status</th><th class="no-print">Actions</th></tr></thead><?php endif; ?>
        <tbody><?php foreach ($waitingRows as $v): ?>
            <?php if ($waitingSchedule): ?><tr><td><?= tdc_e($v['VisitReference']) ?></td><td><?= tdc_e($v['PatientName']) ?></td><td><?= tdc_e(date('Y-m-d', strtotime($v['VisitDate']))) ?></td><td><?= tdc_e(date('H:i', strtotime($v['VisitDate']))) ?></td><td><?= tdc_badge($v['PaymentStatus']) ?></td><td><?= tdc_e(number_format((float)($v['DueBalance'] ?? 0), 2)) ?></td><td><?= tdc_badge($v['QueueStatus']) ?></td><td class="no-print"><button type="button" class="btn-sm schedule-details" data-reference="<?= tdc_e($v['VisitReference']) ?>" data-patient="<?= tdc_e($v['PatientName']) ?>" data-date="<?= tdc_e(date('Y-m-d', strtotime($v['VisitDate']))) ?>" data-time="<?= tdc_e(date('H:i', strtotime($v['VisitDate']))) ?>" data-payment="<?= tdc_e($v['PaymentStatus']) ?>" data-due="<?= tdc_e(number_format((float)($v['DueBalance'] ?? 0), 2)) ?>" data-status="<?= tdc_e($v['QueueStatus']) ?>">Details</button></td></tr>
            <?php else: ?><tr><td><?= tdc_e($v['VisitReference']) ?></td><td><?= tdc_e($v['PatientName']) ?></td><td><?= tdc_e($v['Gender']) ?></td><td><?= tdc_e((string)$v['Age']) ?></td><td><?= tdc_e($v['PatientPhone']) ?></td><td><?= tdc_e(date('Y-m-d', strtotime((string)$v['VisitDate']))) ?></td><td><?= tdc_badge($v['PaymentStatus']) ?></td><td><?= tdc_e(number_format((float)($v['DueBalance'] ?? 0), 2)) ?></td><td><?= tdc_badge($v['QueueStatus']) ?></td><td class="no-print"><div class="row-actions">
                <?php $visitReadyForOrders = in_array((string)($v['QueueStatus'] ?? ''), ['In Consultation', 'Completed'], true) && trim((string)($v['ClinicalNotes'] ?? '')) !== '' && trim((string)($v['Diagnosis'] ?? '')) !== ''; ?>
                <?php if (in_array($v['QueueStatus'], ['Waiting', 'Pending Payment'], true) && tdc_can('consultations.edit')): ?><form method="post" action="doctors.php?workspace=1"><input type="hidden" name="csrf_token" value="<?= tdc_e($csrfToken) ?>"><input type="hidden" name="VisitID" value="<?= (int)$v['VisitID'] ?>"><input type="hidden" name="PatientID" value="<?= (int)$v['PatientID'] ?>"><input type="hidden" name="DoctorID" value="<?= (int)$v['DoctorID'] ?>"><input type="hidden" name="portal_action" value="start"><button type="submit" class="btn-sm btn-primary" data-doctor-action="call" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="Call / Start">Call</button></form><?php endif; ?>
                <button type="button" class="btn-sm" data-doctor-action="consultation" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>"><?= in_array($v['QueueStatus'], ['Waiting', 'Pending Payment'], true) ? 'Start Consultation' : ($v['QueueStatus'] === 'Completed' ? 'View Consultation' : 'Continue Consultation') ?></button>
                <button type="button" class="btn-sm btn-secondary" data-doctor-action="history" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="Medical History">History</button>
                <?php if ((string)($v['EditableLaboratoryID'] ?? '') !== ''): ?><button type="button" class="btn-sm btn-success" data-doctor-action="edit_lab" data-reference="<?= tdc_e((string)$v['EditableLaboratoryID']) ?>" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="Edit Lab Request">Edit Lab</button><?php else: ?><button type="button" class="btn-sm btn-success" data-doctor-action="lab" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="<?= $visitReadyForOrders ? 'Request Lab' : 'Complete the consultation assessment before requesting laboratory tests.' ?>" <?= $visitReadyForOrders ? '' : 'disabled aria-disabled="true"' ?>>Lab</button><?php endif; ?>
                <?php if ((string)($v['EditablePrescriptionReference'] ?? '') !== ''): ?><button type="button" class="btn-sm btn-success" data-doctor-action="edit_prescription" data-reference="<?= tdc_e((string)$v['EditablePrescriptionReference']) ?>" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="Edit Prescription">Edit Prescription</button><?php else: ?><button type="button" class="btn-sm btn-success" data-doctor-action="prescription" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="<?= $visitReadyForOrders ? 'Create Prescription' : 'Complete the consultation assessment before creating a prescription.' ?>" <?= $visitReadyForOrders ? '' : 'disabled aria-disabled="true"' ?>>Prescription</button><?php endif; ?>
                <button type="button" class="btn-sm btn-clinical" data-doctor-action="results" data-visit-id="<?= (int)$v['VisitID'] ?>" data-patient-id="<?= (int)$v['PatientID'] ?>" title="Lab Results">Results</button>
            </div></td></tr><?php endif; ?>
        <?php endforeach; ?>
        <?php if (!$waitingRows): ?><tr><td colspan="<?= $waitingSchedule ? 8 : 10 ?>">No visits match these filters.</td></tr><?php endif; ?></tbody>
    </table></div>
    <?= tdc_pager($waitingPage,$waitingPerPage,$waitingTotal,$waitingFilters) ?>
</section>
<?php if ($waitingSchedule): ?><section class="doctor-schedule-modal" id="doctorScheduleModal" aria-labelledby="doctorScheduleTitle"><button type="button" class="doctor-schedule-close" aria-label="Close">&times;</button><h2 id="doctorScheduleTitle">Visit Details</h2><dl><dt>Visit Ref</dt><dd data-detail="reference"></dd><dt>Patient</dt><dd data-detail="patient"></dd><dt>Date</dt><dd data-detail="date"></dd><dt>Time</dt><dd data-detail="time"></dd><dt>Payment Status</dt><dd><span data-detail="payment" class="doctor-schedule-badge"></span></dd><dt>Due</dt><dd data-detail="due"></dd><dt>Queue Status</dt><dd><span data-detail="status" class="doctor-schedule-badge"></span></dd></dl><button type="button" class="btn btn-secondary doctor-schedule-close">Close</button></section><script>(function(){const modal=document.getElementById('doctorScheduleModal');if(!modal)return;function setBadge(target,value,type){target.textContent=value;target.className='doctor-schedule-badge '+type+'-'+value.toLowerCase().replace(/\s+/g,'-');}document.querySelectorAll('.schedule-details').forEach(function(button){button.addEventListener('click',function(){const payment=modal.querySelector('[data-detail="payment"]');const status=modal.querySelector('[data-detail="status"]');Object.keys(button.dataset).forEach(function(key){const target=modal.querySelector('[data-detail="'+key+'"]');if(!target)return;if(key==='payment')setBadge(target,button.dataset[key],'payment');else if(key==='status')setBadge(target,button.dataset[key],'queue');else target.textContent=button.dataset[key];});modal.classList.add('is-open');});});modal.querySelectorAll('.doctor-schedule-close').forEach(function(button){button.addEventListener('click',function(){modal.classList.remove('is-open');});});})();</script><?php endif; ?>
