<?php
// Rendered only inside the existing selected-visit modal templates.
$editLab = null; $editRx = []; $editLabTests = [];
if (!empty($_GET['edit_lab'])) {
    $s=$pdo->prepare('SELECT * FROM laboratory WHERE LaboratoryID=? AND VisitID=? AND PatientID=? AND DoctorID=?');
    $s->execute([$_GET['edit_lab'],$selectedVisit['VisitID'],$selectedVisit['PatientID'],$selectedVisit['DoctorID']]);$editLab=$s->fetch();
    if($editLab) {$s=$pdo->prepare('SELECT ModernTestID FROM lab_order_catalog_bridge WHERE LaboratoryID=? AND IsActive=1');$s->execute([$editLab['LaboratoryID']]);$editLabTests=array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));}
}
if (!empty($_GET['edit_prescription']) && preg_match('/^[A-Za-z0-9]+$/',(string)$_GET['edit_prescription'])) {
    $s=$pdo->prepare('SELECT * FROM prescriptions WHERE PrescriptionID LIKE ? AND VisitID=? AND PatientID=? AND DoctorID=? ORDER BY PrescriptionID');
    $s->execute([$_GET['edit_prescription'].'-%',$selectedVisit['VisitID'],$selectedVisit['PatientID'],$selectedVisit['DoctorID']]);$editRx=$s->fetchAll();
}
?>
<?php if($editLab && tdc_doctor_lab_edit_guard($pdo,$editLab['LaboratoryID'])['editable']): ?>
<form method="post" id="doctorLabEditForm" class="workflow-form" data-lab-catalog='<?= tdc_e(json_encode($doctorLabCatalog, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>' data-initial-tests='<?= tdc_e(json_encode($editLabTests)) ?>'>
    <h2>Edit Lab Request · <?= tdc_e($editLab['LaboratoryID']) ?></h2>
    <p><?= tdc_e($selectedVisit['PatientName'].' · '.$selectedVisit['VisitReference']) ?></p>
    <input type="hidden" name="csrf_token" value="<?= tdc_e($csrfToken) ?>">
    <input type="hidden" name="VisitID" value="<?= (int)$selectedVisit['VisitID'] ?>"><input type="hidden" name="PatientID" value="<?= (int)$selectedVisit['PatientID'] ?>"><input type="hidden" name="DoctorID" value="<?= (int)$selectedVisit['DoctorID'] ?>">
    <input type="hidden" name="portal_action" value="edit_lab"><input type="hidden" name="LaboratoryID" value="<?= tdc_e($editLab['LaboratoryID']) ?>">
    <section class="rx-item-editor" data-lab-editor><div class="rx-section-heading"><div><h3>Stage laboratory test</h3><p>Add one catalogue test at a time, then review the complete request below.</p></div></div><div class="lab-editor-grid"><div class="form-group"><label>Category *</label><select data-lab-category required><option value="">Select category</option></select></div><div class="form-group"><label>Lab Type *</label><select data-lab-type required disabled><option value="">Select type</option></select></div><div class="form-group"><label>Test *</label><select data-lab-test required disabled><option value="">Select test</option></select></div></div><div class="rx-editor-actions"><button type="button" class="btn-success btn" data-lab-stage>+ Add Test</button><button type="button" class="btn-secondary btn-sm" data-lab-update hidden>Update Test</button><button type="button" class="btn-secondary btn-sm" data-lab-cancel hidden>Cancel Edit</button></div><div class="form-error" data-lab-validation hidden></div></section>
    <section class="rx-added-items"><div class="rx-section-heading"><div><h3>Added Laboratory Tests <span class="rx-item-count" data-lab-staged-count>(0)</span></h3></div></div><div class="rx-items-table-wrap"><table class="rx-items-table"><thead><tr><th>#</th><th>Test</th><th>Fee</th><th>Actions</th></tr></thead><tbody data-lab-staged-body></tbody></table></div></section><div data-lab-staged-inputs></div>
    <label for="editLabNote">Clinical Request</label><textarea id="editLabNote" name="Description" maxlength="2000"><?= tdc_e($editLab['Description']) ?></textarea>
    <button type="submit" class="btn-success btn" data-lab-submit>Save Lab Changes</button>
</form>
<?php endif; ?>
<?php if($editRx && tdc_doctor_prescription_edit_guard($pdo,(string)$_GET['edit_prescription'])['editable']): $editMedicines=$pdo->query('SELECT ItemName,QuantityInStock,SalesUnit,SellingPrice FROM inventory ORDER BY ItemName')->fetchAll(); ?>
<form method="post" id="doctorPrescriptionEditForm" class="workflow-form" data-initial-items='<?= tdc_e(json_encode(array_map(static fn($line)=>['id'=>$line['PrescriptionID'],'medication'=>$line['MedicationName'],'quantity'=>(int)$line['Quantity'],'frequency'=>(string)$line['Frequency'],'duration'=>(string)$line['Duration'],'route'=>(string)$line['Route'],'instructions'=>(string)$line['Instructions']],$editRx), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT)) ?>'>
    <h2>Edit Prescription · <?= tdc_e((string)$_GET['edit_prescription']) ?></h2><p><?= tdc_e($selectedVisit['PatientName'].' · '.$selectedVisit['VisitReference']) ?></p>
    <input type="hidden" name="csrf_token" value="<?= tdc_e($csrfToken) ?>"><input type="hidden" name="VisitID" value="<?= (int)$selectedVisit['VisitID'] ?>"><input type="hidden" name="PatientID" value="<?= (int)$selectedVisit['PatientID'] ?>"><input type="hidden" name="DoctorID" value="<?= (int)$selectedVisit['DoctorID'] ?>">
    <input type="hidden" name="portal_action" value="edit_prescription"><input type="hidden" name="PrescriptionReference" value="<?= tdc_e((string)$_GET['edit_prescription']) ?>">
    <section class="rx-item-editor" data-rx-edit-editor><div class="rx-section-heading"><div><h3>Stage medication change</h3><p>Edit one medication at a time, then save the complete prescription together.</p></div></div><div class="form-group"><label>Medication *</label><select data-rx-edit-medication required><option value="">Select medicine</option><?php foreach($editMedicines as $medicine): ?><option value="<?= tdc_e($medicine['ItemName']) ?>" data-stock="<?= (int)$medicine['QuantityInStock'] ?>" data-unit="<?= tdc_e((string)$medicine['SalesUnit']) ?>" data-price="<?= tdc_e((string)$medicine['SellingPrice']) ?>"><?= tdc_e($medicine['ItemName']) ?> (<?= (int)$medicine['QuantityInStock'] ?> available)</option><?php endforeach; ?></select><div class="rx-meta"></div></div><div class="rx-entry-grid"><div class="form-group"><label>Quantity *</label><input data-rx-edit-quantity type="number" min="1" value="1"></div><div class="form-group"><label>Frequency</label><input data-rx-edit-frequency></div><div class="form-group"><label>Duration</label><input data-rx-edit-duration></div></div><div class="rx-entry-grid"><div class="form-group"><label>Route</label><select data-rx-edit-route><option value="">Select route</option><option>Oral</option><option>Topical</option><option>Intravenous (IV)</option><option>Intramuscular (IM)</option><option>Subcutaneous (SC)</option><option>Inhalation</option><option>Sublingual</option><option>Rectal</option><option>Ophthalmic</option><option>Otic</option><option>Nasal</option><option>Other</option></select></div></div><div class="form-group"><label>Instructions / Note</label><textarea data-rx-edit-instructions maxlength="2000"></textarea></div><div class="rx-editor-actions"><button type="button" class="btn-success btn" data-rx-edit-stage>+ Add Item</button><button type="button" class="btn-secondary btn-sm" data-rx-edit-update hidden>Update Item</button><button type="button" class="btn-secondary btn-sm" data-rx-edit-cancel hidden>Cancel Edit</button></div><div class="form-error" data-rx-edit-validation hidden></div></section><section class="rx-added-items"><div class="rx-section-heading"><div><h3>Prescription Items <span class="rx-item-count" data-rx-edit-count>(0)</span></h3></div></div><div class="rx-items-table-wrap"><table class="rx-items-table"><thead><tr><th>#</th><th>Medication</th><th>Qty</th><th>Frequency</th><th>Duration</th><th>Route</th><th>Actions</th></tr></thead><tbody data-rx-edit-body></tbody></table></div></section><div data-rx-edit-inputs></div><div class="workflow-actions"><button class="btn-success btn">Save Prescription Changes</button></div>
</form>
<?php endif; ?>
