-- =====================================================================
-- Tarey Derma Clinic — PRODUCTION INSTALLER (schema + configuration only)
-- =====================================================================
-- Generated by scripts/generate_production_install.php
-- Generated at: 2026-09-16 20:06:44 UTC
--
-- Contains: complete tables, columns, indexes, keys, roles, permissions,
--           role permissions, default MANUAL payment methods, clinic
--           profile defaults and the login/reference infrastructure.
--
-- Deliberately ABSENT (never shipped in a production install):
--   * demo patients / visits / prescriptions / laboratory orders
--   * demo payments, sales or purchases
--   * developer accounts, test users and known SuperAdmin passwords

-- The single root SuperAdmin is created AFTER this file by:
--   php scripts/create_default_superadmin.php
--
-- Payment methods are MANUAL LABELS ONLY. There is no payment gateway
-- integration anywhere in this product.
--
-- Compatible with a fresh InfinityFree database (MySQL 5.7+ /
-- MariaDB 10.x, PHP 8.2).
-- =====================================================================

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------
-- 1. Drop existing application tables (fresh install)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `visits`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `specializations`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `rolepermissions`;
DROP TABLE IF EXISTS `reference_sequences`;
DROP TABLE IF EXISTS `purchases`;
DROP TABLE IF EXISTS `prescriptionsheader`;
DROP TABLE IF EXISTS `prescriptions`;
DROP TABLE IF EXISTS `pharmacysales`;
DROP TABLE IF EXISTS `permissions`;
DROP TABLE IF EXISTS `payments`;
DROP TABLE IF EXISTS `paymentmethods`;
DROP TABLE IF EXISTS `patients`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `login_attempts`;
DROP TABLE IF EXISTS `labservices`;
DROP TABLE IF EXISTS `laborderitems`;
DROP TABLE IF EXISTS `laboratory`;
DROP TABLE IF EXISTS `inventory`;
DROP TABLE IF EXISTS `doctors`;
DROP TABLE IF EXISTS `departments`;
DROP TABLE IF EXISTS `clinicsettings`;
DROP TABLE IF EXISTS `auditlog`;
DROP TABLE IF EXISTS `accounting`;

-- ---------------------------------------------------------------------
-- 2. Schema
-- ---------------------------------------------------------------------

-- TABLE accounting
CREATE TABLE `accounting` (
  `EntryID` varchar(50) NOT NULL,
  `AccountID` varchar(50) NOT NULL,
  `AccountName` varchar(150) NOT NULL,
  `AccountType` enum('Asset','Liability','Equity','Revenue','Expense') NOT NULL,
  `BookType` enum('General Journal','Cash Book','Sales Book','Purchases Book') NOT NULL,
  `TransactionDate` datetime DEFAULT current_timestamp(),
  `ReferenceID` varchar(50) DEFAULT NULL,
  `Description` text NOT NULL,
  `Debit` decimal(12,2) DEFAULT 0.00,
  `Credit` decimal(12,2) DEFAULT 0.00,
  `Balance` decimal(12,2) DEFAULT 0.00,
  `CreatedAt` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`EntryID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE auditlog
CREATE TABLE `auditlog` (
  `AuditID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ActorUserID` int(11) DEFAULT NULL,
  `EventType` varchar(100) NOT NULL,
  `EntityType` varchar(100) NOT NULL,
  `EntityID` varchar(100) DEFAULT NULL,
  `Summary` varchar(500) NOT NULL,
  `ChangesJson` longtext DEFAULT NULL,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`AuditID`),
  KEY `idx_audit_created` (`CreatedAt`),
  KEY `idx_audit_actor` (`ActorUserID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE clinicsettings
CREATE TABLE `clinicsettings` (
  `SettingKey` varchar(100) NOT NULL,
  `SettingValue` text DEFAULT NULL,
  `UpdatedBy` int(11) DEFAULT NULL,
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`SettingKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE departments
CREATE TABLE `departments` (
  `DepartmentID` int(11) NOT NULL AUTO_INCREMENT,
  `DepartmentName` varchar(120) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`DepartmentID`),
  UNIQUE KEY `uq_departments_name` (`DepartmentName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE doctors
CREATE TABLE `doctors` (
  `DoctorID` int(11) NOT NULL AUTO_INCREMENT,
  `UserID` int(11) DEFAULT NULL,
  `DoctorName` varchar(150) NOT NULL,
  `ConsultationFee` decimal(10,2) DEFAULT 0.00,
  `Specialty` varchar(100) DEFAULT NULL,
  `JoinedDate` date DEFAULT NULL,
  `WorkingDays` varchar(20) NOT NULL DEFAULT '1,2,3,4,5',
  `WorkStartTime` time NOT NULL DEFAULT '09:00:00',
  `WorkEndTime` time NOT NULL DEFAULT '17:00:00',
  PRIMARY KEY (`DoctorID`),
  UNIQUE KEY `uq_doctors_user` (`UserID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE inventory
CREATE TABLE `inventory` (
  `ItemID` varchar(50) NOT NULL,
  `Category` varchar(100) DEFAULT NULL,
  `ItemName` varchar(150) NOT NULL,
  `ItemImage` text DEFAULT NULL,
  `QuantityInStock` int(11) NOT NULL DEFAULT 0,
  `SalesUnit` varchar(50) DEFAULT NULL,
  `SellingPrice` decimal(10,2) DEFAULT 0.00,
  `ExpiryDate` date DEFAULT NULL,
  `LastAcquisitionCostPerUnit` decimal(10,4) DEFAULT NULL,
  `ReorderLevel` int(11) DEFAULT 10,
  `SupplierID` int(11) DEFAULT NULL,
  `LastUpdated` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DefaultPurchaseUnit` varchar(50) DEFAULT NULL,
  `UnitsPerPackage` int(11) DEFAULT NULL,
  PRIMARY KEY (`ItemID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE laboratory
CREATE TABLE `laboratory` (
  `LaboratoryID` varchar(50) NOT NULL,
  `PatientID` int(11) NOT NULL,
  `VisitID` int(11) DEFAULT NULL,
  `DoctorID` int(11) DEFAULT NULL,
  `RequestedByUserID` int(11) DEFAULT NULL,
  `ServiceID` int(11) DEFAULT NULL,
  `TestID` int(11) NOT NULL,
  `TestName` varchar(150) NOT NULL,
  `Description` text DEFAULT NULL,
  `TotalAmount` decimal(10,2) DEFAULT 0.00,
  `AmountPaid` decimal(10,2) DEFAULT 0.00,
  `DueBalance` decimal(10,2) DEFAULT 0.00,
  `PaymentStatus` enum('Paid','Unpaid','Partial') DEFAULT 'Unpaid',
  `WorkflowStatus` enum('Requested','Awaiting Payment','Ready','In Progress','Completed','Cancelled') NOT NULL DEFAULT 'Awaiting Payment',
  `IsAvailable` tinyint(1) DEFAULT 1,
  `OrderDate` datetime DEFAULT current_timestamp(),
  `Result` enum('Positive','Negative','Pending') DEFAULT 'Pending',
  `ClinicalResult` text DEFAULT NULL,
  `ResultDate` datetime DEFAULT NULL,
  `ReviewedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`LaboratoryID`),
  KEY `idx_laboratory_visit` (`VisitID`),
  KEY `idx_laboratory_workflow` (`WorkflowStatus`,`PaymentStatus`,`OrderDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE laborderitems
CREATE TABLE `laborderitems` (
  `LabOrderItemID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LaboratoryID` varchar(50) NOT NULL,
  `ServiceID` int(11) NOT NULL,
  `TestName` varchar(150) NOT NULL,
  `UnitPrice` decimal(10,2) NOT NULL DEFAULT 0.00,
  `Result` enum('Positive','Negative','Pending') NOT NULL DEFAULT 'Pending',
  `ClinicalResult` text DEFAULT NULL,
  `ResultDate` datetime DEFAULT NULL,
  PRIMARY KEY (`LabOrderItemID`),
  UNIQUE KEY `uq_lab_order_service` (`LaboratoryID`,`ServiceID`),
  KEY `idx_lab_order_items_order` (`LaboratoryID`),
  KEY `idx_lab_order_items_service` (`ServiceID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE labservices
CREATE TABLE `labservices` (
  `ServiceID` int(11) NOT NULL AUTO_INCREMENT,
  `ServiceName` varchar(150) NOT NULL,
  `Category` varchar(100) DEFAULT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `IsAvailable` tinyint(1) NOT NULL DEFAULT 1,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ServiceID`),
  UNIQUE KEY `uq_lab_services_name` (`ServiceName`),
  KEY `idx_lab_services_active` (`IsActive`,`ServiceName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE login_attempts
CREATE TABLE `login_attempts` (
  `AttemptKey` varchar(191) NOT NULL,
  `FailedCount` int(11) NOT NULL DEFAULT 0,
  `FirstAttempt` datetime NOT NULL,
  `BlockedUntil` datetime DEFAULT NULL,
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`AttemptKey`),
  KEY `idx_login_attempts_blocked` (`BlockedUntil`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE notifications
CREATE TABLE `notifications` (
  `NotificationID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UserID` int(11) DEFAULT NULL,
  `RoleTarget` enum('superuser','receptionuser','doctoruser','pharmacyuser','labuser') DEFAULT NULL,
  `EventType` varchar(50) NOT NULL,
  `Title` varchar(150) NOT NULL,
  `Message` varchar(500) NOT NULL,
  `Link` varchar(255) DEFAULT NULL,
  `IsRead` tinyint(1) NOT NULL DEFAULT 0,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`NotificationID`),
  KEY `idx_notifications_user` (`UserID`,`IsRead`,`CreatedAt`),
  KEY `idx_notifications_role` (`RoleTarget`,`IsRead`,`CreatedAt`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE patients
CREATE TABLE `patients` (
  `PatientID` int(11) NOT NULL AUTO_INCREMENT,
  `PatientName` varchar(150) NOT NULL,
  `PatientPhone` varchar(20) DEFAULT NULL,
  `PatientAddress` text DEFAULT NULL,
  `Gender` enum('Male','Female') DEFAULT NULL,
  `Age` tinyint(4) DEFAULT NULL,
  `DateOfBirth` date DEFAULT NULL,
  `PatientType` varchar(50) DEFAULT NULL,
  `DueBalance` decimal(10,2) DEFAULT 0.00,
  `VisitNumber` int(11) DEFAULT 1,
  `AllocatedDoctor` int(11) DEFAULT NULL,
  `Remark` text DEFAULT NULL,
  `RegisteredAt` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`PatientID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE paymentmethods
CREATE TABLE `paymentmethods` (
  `PaymentMethodID` int(11) NOT NULL AUTO_INCREMENT,
  `MethodName` varchar(80) NOT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `DisplayOrder` int(11) NOT NULL DEFAULT 0,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PaymentMethodID`),
  UNIQUE KEY `uq_payment_methods_name` (`MethodName`),
  KEY `idx_payment_methods_active` (`IsActive`,`DisplayOrder`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE payments
CREATE TABLE `payments` (
  `PaymentID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PaymentReference` varchar(50) NOT NULL,
  `PatientID` int(11) NOT NULL,
  `VisitID` int(11) DEFAULT NULL,
  `LaboratoryID` varchar(50) DEFAULT NULL,
  `PrescriptionReference` varchar(50) DEFAULT NULL,
  `SaleReference` varchar(50) DEFAULT NULL,
  `PurchaseReference` varchar(50) DEFAULT NULL,
  `PaymentType` enum('Consultation','Laboratory','Pharmacy','POS','Supplier') NOT NULL,
  `Amount` decimal(10,2) NOT NULL,
  `PaymentMethod` varchar(80) NOT NULL DEFAULT 'Cash',
  `PaymentStatus` enum('Confirmed','Voided') NOT NULL DEFAULT 'Confirmed',
  `ReversalOfPaymentID` bigint(20) DEFAULT NULL,
  `ReversalReference` varchar(50) DEFAULT NULL,
  `ReversalReason` varchar(500) DEFAULT NULL,
  `ReceivedBy` int(11) DEFAULT NULL,
  `PaidAt` datetime NOT NULL DEFAULT current_timestamp(),
  `Notes` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`PaymentID`),
  UNIQUE KEY `uq_payments_reference` (`PaymentReference`),
  KEY `idx_payments_patient` (`PatientID`),
  KEY `idx_payments_visit` (`VisitID`),
  KEY `idx_payments_type_date` (`PaymentType`,`PaidAt`),
  KEY `idx_payments_reversal` (`ReversalOfPaymentID`),
  KEY `idx_payments_sale` (`SaleReference`),
  KEY `idx_payments_purchase` (`PurchaseReference`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE permissions
CREATE TABLE `permissions` (
  `PermissionID` int(11) NOT NULL AUTO_INCREMENT,
  `PermissionKey` varchar(150) NOT NULL,
  `ModuleName` varchar(100) NOT NULL,
  `ResourceName` varchar(120) NOT NULL,
  `ActionName` varchar(80) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`PermissionID`),
  UNIQUE KEY `uq_permissions_key` (`PermissionKey`),
  KEY `idx_permissions_module` (`ModuleName`,`ResourceName`)
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE pharmacysales
CREATE TABLE `pharmacysales` (
  `SaleID` varchar(50) NOT NULL,
  `ItemID` varchar(50) NOT NULL,
  `ItemName` varchar(150) NOT NULL,
  `Quantity` int(11) NOT NULL DEFAULT 1,
  `UnitPrice` decimal(10,2) DEFAULT 0.00,
  `LineTotal` decimal(10,2) DEFAULT 0.00,
  `CostPerUnitSnapshot` decimal(10,4) DEFAULT NULL,
  `LineCost` decimal(10,2) DEFAULT NULL,
  `TotalAmount` decimal(10,2) DEFAULT 0.00,
  `AmountPaid` decimal(10,2) DEFAULT 0.00,
  `DueBalance` decimal(10,2) DEFAULT 0.00,
  `PaymentStatus` enum('Paid','Unpaid','Partial') DEFAULT 'Paid',
  `CustomerName` varchar(150) DEFAULT NULL,
  `CustomerPhone` varchar(20) DEFAULT NULL,
  `PatientID` int(11) DEFAULT NULL,
  `VisitID` int(11) DEFAULT NULL,
  `SoldBy` int(11) DEFAULT NULL,
  `SaleDate` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`SaleID`),
  KEY `idx_pharmacy_sales_patient` (`PatientID`),
  KEY `idx_pharmacy_sales_visit` (`VisitID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE prescriptions
CREATE TABLE `prescriptions` (
  `PrescriptionID` varchar(50) NOT NULL,
  `PatientID` int(11) NOT NULL,
  `VisitID` int(11) DEFAULT NULL,
  `PatientName` varchar(150) NOT NULL,
  `PatientPhone` varchar(20) DEFAULT NULL,
  `PatientAddress` text DEFAULT NULL,
  `Gender` enum('Male','Female') DEFAULT NULL,
  `Age` tinyint(4) DEFAULT NULL,
  `VisitNumber` int(11) DEFAULT 1,
  `DoctorID` int(11) NOT NULL,
  `MedicationName` varchar(150) NOT NULL,
  `Quantity` int(11) NOT NULL DEFAULT 1,
  `Route` varchar(50) DEFAULT NULL,
  `Dosage` varchar(100) DEFAULT NULL,
  `Frequency` varchar(100) DEFAULT NULL,
  `Duration` varchar(100) DEFAULT NULL,
  `Instructions` text DEFAULT NULL,
  `Status` enum('Pending','Dispensed','Cancelled') NOT NULL DEFAULT 'Pending',
  `DispensedAt` datetime DEFAULT NULL,
  `DispensedBy` int(11) DEFAULT NULL,
  `PharmacySaleReference` varchar(50) DEFAULT NULL,
  `TotalAmount` decimal(10,2) DEFAULT 0.00,
  `AmountPaid` decimal(10,2) DEFAULT 0.00,
  `DueBalance` decimal(10,2) DEFAULT 0.00,
  `PrescriptionDate` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`PrescriptionID`),
  KEY `idx_prescriptions_visit` (`VisitID`),
  KEY `idx_prescriptions_status` (`Status`,`PrescriptionDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE prescriptionsheader
CREATE TABLE `prescriptionsheader` (
  `PrescriptionID` varchar(50) NOT NULL,
  `PrescriptionSerial` varchar(50) NOT NULL,
  `CompanyName` varchar(150) NOT NULL,
  `PhoneNumbers` varchar(50) DEFAULT NULL,
  `CompanyAddress` text DEFAULT NULL,
  `CompanyLogo` text DEFAULT NULL,
  PRIMARY KEY (`PrescriptionID`),
  UNIQUE KEY `PrescriptionSerial` (`PrescriptionSerial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE purchases
CREATE TABLE `purchases` (
  `PurchaseID` varchar(50) NOT NULL,
  `SupplierID` int(11) NOT NULL,
  `ItemID` varchar(50) DEFAULT NULL,
  `SupplierName` varchar(150) NOT NULL,
  `SupplierPhone` varchar(20) DEFAULT NULL,
  `Category` varchar(100) DEFAULT NULL,
  `ItemName` varchar(150) NOT NULL,
  `ItemImage` text DEFAULT NULL,
  `Quantity` int(11) NOT NULL DEFAULT 1,
  `MinimumQuantity` int(11) DEFAULT 10,
  `PurchaseUnit` varchar(50) DEFAULT NULL,
  `ConversionFactor` decimal(10,2) DEFAULT 1.00,
  `SalesUnit` varchar(50) DEFAULT NULL,
  `UnitPrice` decimal(10,2) DEFAULT 0.00,
  `SellingPrice` decimal(10,2) DEFAULT 0.00,
  `ExpiryDate` date DEFAULT NULL,
  `TotalAmount` decimal(10,2) DEFAULT 0.00,
  `AmountPaid` decimal(10,2) DEFAULT 0.00,
  `DueBalance` decimal(10,2) DEFAULT 0.00,
  `PurchaseDate` datetime DEFAULT current_timestamp(),
  `ReferenceNumber` varchar(100) DEFAULT NULL,
  `Discount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `VATAmount` decimal(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`PurchaseID`),
  KEY `idx_purchases_item_date` (`ItemID`,`PurchaseDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE reference_sequences
CREATE TABLE `reference_sequences` (
  `SequenceKey` varchar(80) NOT NULL,
  `NextValue` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`SequenceKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE rolepermissions
CREATE TABLE `rolepermissions` (
  `RoleID` int(11) NOT NULL,
  `PermissionID` int(11) NOT NULL,
  PRIMARY KEY (`RoleID`,`PermissionID`),
  KEY `idx_role_permissions_permission` (`PermissionID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE roles
CREATE TABLE `roles` (
  `RoleID` int(11) NOT NULL AUTO_INCREMENT,
  `RoleKey` varchar(100) NOT NULL,
  `RoleName` varchar(100) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `IsSystem` tinyint(1) NOT NULL DEFAULT 0,
  `IsProtected` tinyint(1) NOT NULL DEFAULT 0,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`RoleID`),
  UNIQUE KEY `uq_roles_key` (`RoleKey`),
  UNIQUE KEY `uq_roles_name` (`RoleName`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE specializations
CREATE TABLE `specializations` (
  `SpecializationID` int(11) NOT NULL AUTO_INCREMENT,
  `SpecializationName` varchar(120) NOT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`SpecializationID`),
  UNIQUE KEY `uq_specializations_name` (`SpecializationName`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE users
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userlegalname` varchar(255) NOT NULL,
  `role` varchar(100) NOT NULL,
  `role_id` int(11) DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_root` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_users_role_id` (`role_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- TABLE visits
CREATE TABLE `visits` (
  `VisitID` int(11) NOT NULL AUTO_INCREMENT,
  `VisitReference` varchar(50) NOT NULL,
  `PatientID` int(11) NOT NULL,
  `DoctorID` int(11) NOT NULL,
  `ReceptionistUserID` int(11) DEFAULT NULL,
  `VisitDate` datetime NOT NULL DEFAULT current_timestamp(),
  `ConsultationFee` decimal(10,2) NOT NULL DEFAULT 0.00,
  `AmountPaid` decimal(10,2) NOT NULL DEFAULT 0.00,
  `DueBalance` decimal(10,2) NOT NULL DEFAULT 0.00,
  `PaymentStatus` enum('Unpaid','Partial','Paid') NOT NULL DEFAULT 'Unpaid',
  `QueueStatus` enum('Pending Payment','Waiting','In Consultation','Completed','Cancelled') NOT NULL DEFAULT 'Pending Payment',
  `ChiefComplaint` text DEFAULT NULL,
  `ClinicalNotes` text DEFAULT NULL,
  `Diagnosis` text DEFAULT NULL,
  `TreatmentPlan` text DEFAULT NULL,
  `FollowUpPlan` text DEFAULT NULL,
  `FollowUpDate` date DEFAULT NULL,
  `CompletedAt` datetime DEFAULT NULL,
  `CreatedAt` datetime NOT NULL DEFAULT current_timestamp(),
  `UpdatedAt` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`VisitID`),
  UNIQUE KEY `uq_visits_reference` (`VisitReference`),
  KEY `idx_visits_patient` (`PatientID`),
  KEY `idx_visits_doctor_queue` (`DoctorID`,`QueueStatus`,`VisitDate`),
  KEY `idx_visits_payment` (`PaymentStatus`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- ---------------------------------------------------------------------
-- 3. Configuration seed
-- ---------------------------------------------------------------------
INSERT IGNORE INTO `roles` (`RoleKey`,`RoleName`,`Description`,`IsSystem`,`IsProtected`,`IsActive`) VALUES
('superuser','SuperAdmin','Full system administration and operational access.',1,1,1),
('receptionuser','Reception','Combined reception, pharmacy, laboratory and accounting operations. Acquisition cost and administration remain restricted.',1,1,1),
('doctoruser','Doctor','Assigned consultations, prescriptions and laboratory requests.',1,1,1),
('labuser','Laboratory','Laboratory order processing and clinical results.',1,1,1),
('pharmacyuser','Pharmacy','Prescription dispensing and point-of-sale operations.',1,1,1);
INSERT IGNORE INTO `permissions` (`PermissionKey`,`ModuleName`,`ResourceName`,`ActionName`,`Description`) VALUES
('dashboard.view','Dashboard','Dashboard','view','View role dashboard'),
('reception.view','Reception','Reception workspace','view','Open reception workspace'),
('patients.view','Patients','Patient records','view','View patient records'),
('patients.create','Patients','Patient records','create','Register patients'),
('patients.edit','Patients','Patient records','edit','Edit patient registration'),
('patients.delete','Patients','Patient records','delete','Delete eligible patient records'),
('patients.history','Patients','Patient history','view','View patient clinical and financial history'),
('patients.import','Patients','Patient records','import','Import patient records from CSV'),
('patients.export','Patients','Patient records','export','Export patient records'),
('visits.view','Visits / Appointments','Visits','view','View visits'),
('visits.create','Visits / Appointments','Visits','create','Create visits'),
('visits.edit','Visits / Appointments','Visits','edit','Edit visits'),
('visits.assign','Visits / Appointments','Doctor assignment','assign','Assign visits to doctors'),
('doctors.view','Doctors','Doctor directory','view','View doctors'),
('doctors.manage','Doctors','Doctor directory','manage','Create and maintain doctor records'),
('doctors.import','Doctors','Doctor directory','import','Import doctor records from CSV'),
('doctors.export','Doctors','Doctor directory','export','Export doctor records'),
('doctor.workspace','Doctors','Doctor workspace','work','Use assigned clinical workspace'),
('consultations.view','Consultations','Consultations','view','View consultations'),
('consultations.create','Consultations','Consultations','create','Book consultations'),
('consultations.edit','Consultations','Clinical record','edit','Record clinical notes'),
('consultations.complete','Consultations','Clinical record','complete','Complete consultations'),
('laboratory.view','Laboratory','Laboratory orders','view','View laboratory orders'),
('laboratory.request','Laboratory','Laboratory orders','request','Request laboratory tests'),
('laboratory.process','Laboratory','Laboratory orders','process','Process paid laboratory orders'),
('laboratory.result.create','Laboratory','Laboratory results','create','Enter laboratory results'),
('laboratory.result.edit','Laboratory','Laboratory results','edit','Edit in-progress laboratory results'),
('laboratory.complete','Laboratory','Laboratory orders','complete','Complete laboratory tests'),
('laboratory.results.view','Laboratory','Laboratory results','view','View laboratory results'),
('lab_billing.view','Laboratory Billing','Laboratory bills','view','View laboratory bills'),
('lab_billing.payment','Laboratory Billing','Laboratory payments','receive','Receive laboratory payments'),
('pharmacy.view','Pharmacy','Pharmacy workspace','view','Open pharmacy workspace'),
('pharmacy.prescriptions.view','Pharmacy','Prescriptions','view','View prescription queue'),
('pharmacy.prescription.create','Pharmacy','Prescriptions','create','Create prescriptions'),
('pharmacy.dispense','Pharmacy','Prescriptions','dispense','Dispense prescriptions'),
('pharmacy.pos','Pharmacy','Point of sale','sell','Use point of sale'),
('pharmacy.purchases.manage','Pharmacy','Purchases','manage','Manage purchases'),
('pharmacy.inventory.view','Inventory','Inventory','view','View medicine inventory'),
('pharmacy.inventory.manage','Inventory','Inventory','manage','Manage medicine inventory'),
('pharmacy_billing.view','Pharmacy Billing','Pharmacy bills','view','View pharmacy billing'),
('pharmacy_billing.payment','Pharmacy Billing','Pharmacy payments','receive','Receive pharmacy payments'),
('accounting.view','Accounting','Accounting','view','View accounting'),
('accounting.transactions.view','Accounting','Transactions','view','View accounting transactions'),
('accounting.journal.post','Accounting','Advanced accounting','post','Post manual journal entries'),
('accounting.journal.reverse','Accounting','Advanced accounting','reverse','Reverse manual journal entries'),
('accounting.expenses.create','Accounting','Expenses','create','Create expense entries'),
('accounting.expenses.edit','Accounting','Expenses','edit','Reverse or correct expense entries'),
('reports.view','Reports','Reports','view','View reports'),
('reports.export','Reports','Reports','export','Export reports'),
('reports.income.cost.view','Reports','Income Statement','view cost','View aggregate pharmacy cost and profit in the Income Statement'),
('setup.view','Setup','Setup','view','Open system Setup'),
('setup.organization.manage','Setup','Organization','manage','Manage clinic organization'),
('setup.users.manage','Users','Users','manage','Manage user accounts'),
('setup.roles.manage','Roles & Permissions','Roles','manage','Manage roles'),
('setup.permissions.manage','Roles & Permissions','Permissions','manage','Manage role permissions'),
('setup.clinical.manage','Setup','Clinical setup','manage','Manage clinical master data'),
('setup.laboratory.manage','Setup','Laboratory setup','manage','Manage laboratory catalogue'),
('setup.pharmacy.manage','Setup','Pharmacy setup','manage','Manage pharmacy master data'),
('setup.financial.manage','Setup','Financial setup','manage','Manage payment methods'),
('setup.communication.manage','Setup','Communication','manage','Manage supported communications'),
('setup.system.manage','System','System setup','manage','Manage system settings and audit log'),
('payments.reverse','Accounting','Payments','reverse','Reverse or void recorded manual payments'),
('pharmacy.purchase_cost.view','Pharmacy','Purchase costs','view','View confidential supplier acquisition costs');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='superuser' AND p.`PermissionKey` IN ('dashboard.view','reception.view','patients.view','patients.create','patients.edit','patients.delete','patients.history','patients.import','patients.export','visits.view','visits.create','visits.edit','visits.assign','doctors.view','doctors.manage','doctors.import','doctors.export','doctor.workspace','consultations.view','consultations.create','consultations.edit','consultations.complete','laboratory.view','laboratory.request','laboratory.process','laboratory.result.create','laboratory.result.edit','laboratory.complete','laboratory.results.view','lab_billing.view','lab_billing.payment','pharmacy.view','pharmacy.prescriptions.view','pharmacy.prescription.create','pharmacy.dispense','pharmacy.pos','pharmacy.purchases.manage','pharmacy.inventory.view','pharmacy.inventory.manage','pharmacy_billing.view','pharmacy_billing.payment','accounting.view','accounting.transactions.view','accounting.journal.post','accounting.journal.reverse','accounting.expenses.create','accounting.expenses.edit','reports.view','reports.export','setup.view','setup.organization.manage','setup.users.manage','setup.roles.manage','setup.permissions.manage','setup.clinical.manage','setup.laboratory.manage','setup.pharmacy.manage','setup.financial.manage','setup.communication.manage','setup.system.manage','payments.reverse','pharmacy.purchase_cost.view');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='receptionuser' AND p.`PermissionKey` IN ('dashboard.view','reception.view','patients.view','patients.create','patients.edit','patients.delete','patients.history','patients.import','patients.export','visits.view','visits.create','visits.edit','visits.assign','consultations.view','consultations.create','lab_billing.view','lab_billing.payment','pharmacy_billing.view','pharmacy_billing.payment','pharmacy.view','pharmacy.prescriptions.view','pharmacy.dispense','pharmacy.pos','pharmacy.inventory.view','pharmacy.inventory.manage','laboratory.view','laboratory.process','laboratory.result.create','laboratory.result.edit','laboratory.complete','laboratory.results.view','accounting.view','accounting.transactions.view','accounting.expenses.create','accounting.expenses.edit','reports.view','reports.export');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='doctoruser' AND p.`PermissionKey` IN ('dashboard.view','doctors.view','doctor.workspace','patients.history','consultations.view','consultations.edit','consultations.complete','laboratory.request','laboratory.results.view','pharmacy.prescription.create');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='labuser' AND p.`PermissionKey` IN ('dashboard.view','laboratory.view','laboratory.process','laboratory.result.create','laboratory.result.edit','laboratory.complete','laboratory.results.view');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='pharmacyuser' AND p.`PermissionKey` IN ('dashboard.view','pharmacy.view','pharmacy.prescriptions.view','pharmacy.dispense','pharmacy.pos','pharmacy.inventory.view','pharmacy.inventory.manage','pharmacy.purchases.manage');
INSERT IGNORE INTO `rolepermissions` (`RoleID`,`PermissionID`) SELECT r.`RoleID`, p.`PermissionID` FROM `roles` r CROSS JOIN `permissions` p WHERE r.`RoleKey`='superuser' AND p.`PermissionKey`='reports.income.cost.view';
INSERT IGNORE INTO `paymentmethods` (`MethodName`,`Description`,`IsActive`,`DisplayOrder`) VALUES
('Cash','Physical cash received at the cashier desk.',1,1),
('EVC Plus','Manual EVC Plus mobile wallet transfer (recorded by hand).',1,2),
('Mobile Money','Manual mobile money transfer (recorded by hand).',1,3),
('Bank Transfer','Manual bank transfer (recorded by hand).',1,4),
('Card','Manual card terminal settlement (recorded by hand).',1,5),
('Cheque','Manual cheque deposit (recorded by hand).',1,6),
('Other','Any other manual settlement method.',1,7);
INSERT IGNORE INTO `clinicsettings` (`SettingKey`,`SettingValue`) VALUES
('ClinicName','Tarey Derma Clinic'),
('Currency','USD');

-- No users are seeded. Run the password-supplied bootstrap command next.
-- No patients, clinical records, payments, sales, purchases or audit rows are seeded.

-- =====================================================================
-- END PRODUCTION INSTALLER
-- =====================================================================
