<?php
// Included by the disposable-schema role test runner; never writes clinic data.
$purchasePost = ['form_action'=>'save','SupplierName'=>'Confidential Supplier','SupplierPhone'=>'','ReferenceNumber'=>'COST-TEST','PurchaseDate'=>date('Y-m-d'),'ItemName'=>['Test Cream'],'Category'=>['Medicine'],'Quantity'=>['2'],'UnitPrice'=>['731.29'],'SellingPrice'=>['19.50'],'PurchaseUnit'=>['Box'],'SalesUnit'=>['Tube'],'ConversionFactor'=>['6'],'ExpiryDate'=>['2028-12-31'],'Discount'=>'10','VATAmount'=>'2','AmountPaid'=>'100'];
$cases[] = ['name'=>'SuperAdmin purchase conversion and partial payment','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases'],'post'=>$purchasePost,'status'=>302,'sql'=>[["SELECT UnitPrice FROM Purchases WHERE ReferenceNumber='COST-TEST'",'731.29'],["SELECT TotalAmount FROM Purchases WHERE ReferenceNumber='COST-TEST'",'1454.58'],["SELECT DueBalance FROM Purchases WHERE ReferenceNumber='COST-TEST'",'1354.58'],["SELECT ConversionFactor FROM Purchases WHERE ReferenceNumber='COST-TEST'",'6.00']]];
$cases[] = ['snapshot'=>'purchase','name'=>'SuperAdmin purchase form modal','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases','new'=>'1'],'contains'=>['id="purchaseModal"','Purchase Price','Advanced'],'absent'=>['Fatal error','Warning:']];
$cases[] = ['name'=>'SuperAdmin cost detail visible','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases','view'=>'PO000001'],'contains'=>['731.29','1,454.58'],'absent'=>['Warning:']];
$cases[] = ['name'=>'SuperAdmin cost export visible','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases','export'=>'csv'],'contains'=>['1454.58']];
foreach (['Discount'=>'2000','AmountPaid'=>'2000','ExpiryDate'=>['2026-02-31'],'Quantity'=>['0'],'UnitPrice'=>['-1'],'SellingPrice'=>['']] as $field=>$invalid) {
    $cases[] = ['name'=>'Purchase rejects invalid '.$field,'role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases'],'post'=>array_replace($purchasePost,[$field=>$invalid]),'sql'=>[["SELECT COUNT(*) FROM Purchases WHERE ReferenceNumber='COST-TEST'",'1']],'contains'=>['error-msg']];
}
foreach (['pharmacyuser','doctoruser','receptionuser','labuser'] as $role) {
    if ($role === 'labuser') $cases[] = ['name'=>'Restore disposable deleted lab fixture','role'=>'superuser','page'=>'home.php','before_sql'=>["INSERT INTO users (userlegalname,role,role_id,username,password,is_active,is_root) SELECT 'Test lab','labuser',RoleID,'labuser','unused',1,0 FROM Roles WHERE RoleKey='labuser'"]];
    // Explicit grants exercise the cost boundary independently of page access.
    $grant = "INSERT IGNORE INTO RolePermissions (RoleID,PermissionID) SELECT r.RoleID,p.PermissionID FROM Roles r CROSS JOIN Permissions p WHERE r.RoleKey='$role' AND p.PermissionKey IN ('pharmacy.view','pharmacy.purchases.manage','pharmacy.inventory.view','reports.view','reports.export')";
    foreach ([['section'=>'purchases'],['section'=>'purchases','view'=>'PO000001'],['section'=>'purchases','export'=>'csv'],['section'=>'purchases','format'=>'json'],['section'=>'purchases','print'=>'1'],['section'=>'inventory']] as $i=>$get) {
        $cases[] = ['name'=>"$role cost confidentiality surface $i",'role'=>$role,'page'=>'pharmacy.php','before_sql'=>[$grant],'get'=>$get,'absent'=>['731.29','1454.58','1,454.58','1354.58','1,354.58','Purchase Price','name="UnitPrice[]"','Warning:','Fatal error']];
    }
    foreach (['new','post','report'] as $surface) {
        $cases[] = ['name'=>"$role direct cost denial $surface",'role'=>$role,'page'=>$surface === 'report' ? 'reports.php' : 'pharmacy.php','get'=>$surface === 'report' ? ['section'=>'pharmacy-purchases','export'=>'csv'] : ['section'=>'purchases'] + ($surface === 'new' ? ['new'=>'1'] : []),'post'=>$surface === 'post' ? $purchasePost : [],'status'=>403,'absent'=>['731.29']];
    }
}
$cases[] = ['snapshot'=>'waiting','name'=>'SuperAdmin waiting table all doctors','role'=>'superuser','page'=>'doctors.php','get'=>['workspace'=>'1'],'contains'=>['Patient Waiting','Other Patient','Test Patient'],'absent'=>['Warning:','Fatal error']];
$cases[] = ['name'=>'Doctor waiting export stays assigned','role'=>'doctoruser','page'=>'doctors.php','get'=>['export'=>'csv'],'contains'=>['Test Patient'],'absent'=>['Other Patient','731.29']];
$cases[] = ['name'=>'Waiting search filters actual visits','role'=>'superuser','page'=>'doctors.php','get'=>['workspace'=>'1','q'=>'Other Patient'],'contains'=>['Other Patient'],'absent'=>['>Test Patient<']];
$cases[] = ['name'=>'Waiting date range rejects invalid dates','role'=>'superuser','page'=>'doctors.php','get'=>['workspace'=>'1','from_date'=>'2026-02-31'],'contains'=>['From Date is not a valid date.'],'absent'=>['>Test Patient<']];
foreach (['start'=>[], 'save_notes'=>['Diagnosis'=>'SuperAdmin clinical test','complete'=>'1'], 'prescribe'=>['MedicationName'=>['Test Cream'],'Quantity'=>['1']], 'request_lab'=>['ServiceID'=>['1']]] as $action=>$post) {
$cases[] = ['name'=>'SuperAdmin real doctor action '.$action,'role'=>'superuser','page'=>'doctors.php','get'=>['workspace'=>'1'],'post'=>['portal_action'=>$action,'VisitID'=>'1']+$post,'status'=>302,'session_role_expected'=>'superuser','sql'=>$action==='save_notes' ? [["SELECT QueueStatus FROM Visits WHERE VisitID=1",'Completed'],["SELECT Diagnosis FROM Visits WHERE VisitID=1",'SuperAdmin clinical test']] : []];
}
$cases[] = ['name'=>'SuperAdmin starts another doctor visit without impersonation','role'=>'superuser','page'=>'doctors.php','get'=>['workspace'=>'1'],'post'=>['portal_action'=>'start','VisitID'=>'3'],'status'=>302,'session_role_expected'=>'superuser','sql'=>[["SELECT QueueStatus FROM Visits WHERE VisitReference='VISOTHER'",'In Consultation']]];
$cases[] = ['name'=>'Purchase stock and expiry were persisted','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'inventory'],'sql'=>[["SELECT QuantityInStock FROM Inventory WHERE ItemID='ITM000001'",'20'],["SELECT ExpiryDate FROM Inventory WHERE ItemID='ITM000001'",'2028-12-31']]];
$cases[] = ['name'=>'Purchase reuses configured pack conversion','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases'],'post'=>array_replace($purchasePost,['ConversionFactor'=>[''],'SalesUnit'=>[''],'PurchaseUnit'=>[''],'ReferenceNumber'=>'REUSE-TEST']),'status'=>302,'sql'=>[["SELECT ConversionFactor FROM Purchases WHERE ReferenceNumber='REUSE-TEST'",'6.00'],["SELECT QuantityInStock FROM Inventory WHERE ItemID='ITM000001'",'32']]];
$cases[] = ['name'=>'Purchase void reverses converted stock','role'=>'superuser','page'=>'pharmacy.php','get'=>['section'=>'purchases'],'post'=>['form_action'=>'void','PORef'=>'PO000002'],'status'=>302,'sql'=>[["SELECT QuantityInStock FROM Inventory WHERE ItemID='ITM000001'",'20'],["SELECT COUNT(*) FROM Purchases WHERE ReferenceNumber='REUSE-TEST'",'0']]];
