import { spawn } from 'node:child_process';
import { writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const port=9334, profile=join(tmpdir(),`tdc-setup-qa-${Date.now()}`);
const chrome=spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--window-size=1440,1000','http://127.0.0.1:8137/auth/auth.php'],{stdio:'ignore'});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));let socket,id=0;const pending=new Map();
async function connect(){for(let i=0;i<40;i++){try{const pages=await fetch(`http://127.0.0.1:${port}/json`).then(r=>r.json());const page=pages.find(p=>p.type==='page');if(page){socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});socket.addEventListener('message',event=>{const m=JSON.parse(event.data);if(!m.id||!pending.has(m.id))return;const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)});return}}catch{}await sleep(250)}throw new Error('Chrome DevTools unavailable')}
function command(method,params={}){const commandId=++id;return new Promise((resolve,reject)=>{pending.set(commandId,{resolve,reject});socket.send(JSON.stringify({id:commandId,method,params}))})}
async function shot(path){const r=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(path,Buffer.from(r.data,'base64'))}
try{await connect();await command('Page.enable');await command('Runtime.enable');await sleep(700);await command('Runtime.evaluate',{expression:`document.querySelector('#username').value='uat_superadmin';document.querySelector('#password').value='TareySA#926!';document.querySelector('#loginForm').submit()`});await sleep(1000);await command('Page.navigate',{url:'http://127.0.0.1:8137/auth/pages/setup.php'});await sleep(900);await shot('setup-desktop.png');await command('Page.navigate',{url:'http://127.0.0.1:8137/auth/pages/setup.php?section=permissions'});await sleep(900);await command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await command('Page.reload',{ignoreCache:true});await sleep(900);const metrics=await command('Runtime.evaluate',{expression:`({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,profile:!!document.querySelector('.profile-trigger'),settings:[...document.querySelectorAll('.nav-link')].some(a=>a.textContent.trim()==='Settings'),setup:[...document.querySelectorAll('.nav-link')].some(a=>a.textContent.trim()==='Setup')})`,returnByValue:true});console.log(JSON.stringify(metrics.result.value));await shot('setup-permissions-mobile.png')}finally{socket?.close();chrome.kill();await sleep(250);await rm(profile,{recursive:true,force:true}).catch(()=>{})}
